#############################################################################
# Makefile for building: NetworkMonitor
# Generated by qmake (3.0) (Qt 5.4.1)
# Project:  NetworkMonitor.pro
# Template: app
# Command: /home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile NetworkMonitor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I. -I../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/include -I../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/include/QtCore -I. -I../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/linux-g++
QMAKE         = /home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = NetworkMonitor1.0.0
DISTDIR = /home/rb/devel/libpcap/networkMonitor/NetworkMonitor/.tmp/NetworkMonitor1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64 -Wl,-rpath,/home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -lpcap -L/home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/lib -lQt5Core -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.c 
OBJECTS       = main.o
DIST          = ../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/linux.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/qconfig.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resources.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/moc.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/lex.prf \
		NetworkMonitor.pro  main.c
QMAKE_TARGET  = NetworkMonitor
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = NetworkMonitor


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: NetworkMonitor.pro ../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/linux.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/qconfig.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resources.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/moc.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/lex.prf \
		NetworkMonitor.pro \
		/home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile NetworkMonitor.pro
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/unix.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/linux.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/qconfig.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_pre.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/default_post.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/qt.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/resources.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/moc.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/unix/thread.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/yacc.prf:
../../../SDK/Qt/Qt-5.4.0/5.4/gcc_64/mkspecs/features/lex.prf:
NetworkMonitor.pro:
/home/rb/devel/SDK/Qt/Qt-5.4.0/5.4/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile NetworkMonitor.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents main.c $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all:
compiler_moc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.c 
	$(CC) -c $(CFLAGS) $(INCPATH) -o main.o main.c

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

